Added Reservations to the homepage
tomasvdlaan/cgi-res-frontend pull request #15
Opened 2022-05-12 11:43 UTC by Vincent-Maximus

Approve this pls xD

2022-05-13 14:24 UTC, BlackBearFTW requested changes
Haal moment.js weg en vervang `timeStart` en `timeEnd` met
```
        public static getTimeString(date: Date) {
          return `${date.getHours().toString().padStart(2, '0')}:${date.toString().padStart(2, '0')}`
        }
```
 vervang `dateStringer` met        
```
public static getMinifiedDateString(date: Date) {
        const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
        return `${date.getDate()} ${days[date.getDay()]}`;
    }
```
Dit kan eventueel nog in de config.json file worden geplaatst (`daysShort`)
`const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];`

2022-05-13 14:24 UTC, BlackBearFTW commented on src/pages/home/HomePage.tsx
> +	const timeStart = (start: Date) => {
Plaats dit in een losse utility of helper

2022-05-19 09:46 UTC, BlackBearFTW requested changes, later dismissed
Looks good!, maar deze heeft wel een infinite loop dus dat moet eerst worden opgezocht

2022-06-15 09:03 UTC, tomasvdlaan approved these changes
Top werk geleverd guys

2022-06-15 09:04 UTC, merged